import React, { useEffect, useRef } from "react";
import { AccessibilityResult } from "@/types/accessibility";
import { X, FileText, Download, Copy, Check } from "lucide-react";

interface Props {
  isOpen: boolean;
  onClose: () => void;
  result: AccessibilityResult;
  inputCode: string;
}

export const ExportModal: React.FC<Props> = ({ isOpen, onClose, result, inputCode }) => {
  const [copied, setCopied] = React.useState(false);
  const modalRef = useRef<HTMLDivElement>(null);
  const closeBtnRef = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    if (isOpen) {
      closeBtnRef.current?.focus();
      const handleKeyDown = (e: KeyboardEvent) => {
        if (e.key === "Escape") {
          onClose();
        }
      };
      window.addEventListener("keydown", handleKeyDown);
      return () => window.removeEventListener("keydown", handleKeyDown);
    }
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  const generateMarkdownReport = (): string => {
    return `# AccessiCraft AI - Accessibility Compliance Audit Report
Generated: ${new Date(result.timestamp).toUTCString()}
Compliance Rating: ${result.complianceLevel} (Score: ${result.score}/100)
Engine: ${result.engine}

## Executive Summary
${result.summary}

## Detected Violations (${result.issues.length})
${result.issues.map((issue, idx) => `
### ${idx + 1}. [${issue.severity.toUpperCase()}] ${issue.title}
- **Criterion**: ${issue.criterion}
- **Principle**: ${issue.principle}
- **Level**: WCAG ${issue.level}
- **Description**: ${issue.description}
- **User Impact**: ${issue.impact}
- **Recommendation**: ${issue.recommendation}
${issue.codeSnippet ? `\`\`\`html\n${issue.codeSnippet}\n\`\`\`` : ''}
`).join("\n")}

## Key Architectural Enhancements
${result.keyImprovements.map(imp => `- ${imp}`).join("\n")}

## Screen Reader Announcement Sequence
${result.screenReaderWalkthrough.map(step => `
- **Step ${step.step}** (${step.focusedElement}): Key: \`${step.keyboardAction}\`
  - *Vocalizes*: "${step.announcedText}"
  - *Context*: ${step.annotation}
`).join("\n")}

## Remediated Production Code
\`\`\`html
${result.remediatedCode}
\`\`\`

---
*Report generated by AccessiCraft AI — W3C WCAG 2.1 AA Compliance Suite.*
`;
  };

  const handleDownloadMarkdown = () => {
    const markdown = generateMarkdownReport();
    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `accessicraft-audit-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadJSON = () => {
    const data = JSON.stringify(result, null, 2);
    const blob = new Blob([data], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `accessicraft-audit-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopyMarkdown = async () => {
    const markdown = generateMarkdownReport();
    await navigator.clipboard.writeText(markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  };

  return (
    <div
      role="presentation"
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm"
      onClick={e => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div
        ref={modalRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby="export-modal-title"
        aria-describedby="export-modal-desc"
        className="w-full max-w-lg bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 shadow-2xl space-y-4"
      >
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-blue-600 dark:text-blue-400" aria-hidden="true" />
            <h3 id="export-modal-title" className="text-lg font-bold text-slate-900 dark:text-white">
              Export Compliance Audit Report
            </h3>
          </div>
          <button
            ref={closeBtnRef}
            type="button"
            onClick={onClose}
            aria-label="Close export dialog"
            className="p-1.5 rounded-lg text-slate-500 hover:text-slate-800 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors focus-visible:ring-2 focus-visible:ring-blue-600 focus-visible:outline-none"
          >
            <X className="w-5 h-5" aria-hidden="true" />
          </button>
        </div>

        <p id="export-modal-desc" className="text-xs text-slate-600 dark:text-slate-400">
          Share your WCAG 2.1 compliance audit with engineering teammates, QA, and accessibility officers.
        </p>

        <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-2 text-xs">
          <div className="flex justify-between">
            <span className="text-slate-500">Audit Status:</span>
            <span className="font-semibold text-slate-900 dark:text-white">{result.complianceLevel} ({result.score}/100)</span>
          </div>
          <div className="flex justify-between">
            <span className="text-slate-500">Violations Documented:</span>
            <span className="font-semibold text-slate-900 dark:text-white">{result.issues.length} Issues</span>
          </div>
          <div className="flex justify-between">
            <span className="text-slate-500">Audit Engine:</span>
            <span className="font-semibold text-slate-900 dark:text-white">{result.engine}</span>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5 pt-2">
          <button
            type="button"
            onClick={handleDownloadMarkdown}
            className="flex items-center justify-center gap-1.5 px-3 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold shadow-sm transition-colors focus-visible:ring-2 focus-visible:ring-blue-600 focus-visible:outline-none"
          >
            <Download className="w-4 h-4" aria-hidden="true" />
            <span>Markdown</span>
          </button>

          <button
            type="button"
            onClick={handleDownloadJSON}
            className="flex items-center justify-center gap-1.5 px-3 py-2.5 rounded-xl border border-slate-300 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-800 dark:text-slate-200 text-xs font-semibold transition-colors focus-visible:ring-2 focus-visible:ring-blue-600 focus-visible:outline-none"
          >
            <Download className="w-4 h-4" aria-hidden="true" />
            <span>JSON</span>
          </button>

          <button
            type="button"
            onClick={handleCopyMarkdown}
            className="flex items-center justify-center gap-1.5 px-3 py-2.5 rounded-xl border border-slate-300 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-800 dark:text-slate-200 text-xs font-semibold transition-colors focus-visible:ring-2 focus-visible:ring-blue-600 focus-visible:outline-none"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-emerald-500" aria-hidden="true" />
                <span>Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" aria-hidden="true" />
                <span>Copy MD</span>
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};
